### PR TITLE
practice question4-7 on 12/06/2023

### PR DESCRIPTION
**Pull request by Depton**

### CODE REVIEW

**Review by beauclair36 — COMMENTED** [review]
Good job

**Review by Ismaelguedjo — COMMENTED** [review]
Good

**Review by Depton — COMMENTED** [review]
where is the commit?

**Review by beauclair36 — COMMENTED** [review]
Good job

**Review by Ismaelguedjo — COMMENTED** [review]
Wonderful Job

**Review by Ismaelguedjo — COMMENTED** [review]
Great

**Review by Ismaelguedjo — APPROVED** [review]
Great Job

**Comment by beauclair36** [comment]
Good job

**Comment by beauclair36** [comment]
Nice job

**Pull request merged**
